name: Build, Scan, Push Docker & Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  build_scan_push_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      PROJECT_NAME: simple-time-service
      CONTAINER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/simple-time-service:latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies & build
      - name: Install & Build
        working-directory: ./app
        run: |
          npm install
          npm run build

      # Step 4: Docker Login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build Docker Image
      - name: Build Docker Image
        working-directory: ./app
        run: |
          docker build -t $CONTAINER_IMAGE .

      # Step 6: Trivy Scan
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $CONTAINER_IMAGE
          format: table
          exit-code: 0
          severity: CRITICAL

      # Step 7: Push Docker Image
      - name: Push Docker Image
        run: |
          docker push $CONTAINER_IMAGE